# Generated by Django 6.0 on 2026-04-11 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Дава достъп до admin панела. В комбинация със SUPER_ADMIN и "Статут на супер-потребител" дава пълен достъп.', verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='При активиране заедно с роля SUPER_ADMIN, потребителят получава всички права (супер админ).', verbose_name='Статут на супер-потребител'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(help_text='За супер админ: избери роля SUPER_ADMIN + включи "Администратор" и "Статут на супер-потребител". За общинар е достатъчно да избереш роля MUNICIPAL_ADMIN.', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role', verbose_name='Роля'),
        ),
    ]
