# Generated by Django 6.0 on 2025-12-21 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заглавие')),
                ('content', models.TextField(verbose_name='Съдържание')),
                ('source_type', models.CharField(choices=[('MUNICIPALITY', 'Община'), ('EMERGENCY', 'Извънредно'), ('ANNOUNCEMENT', 'Съобщение')], max_length=20, verbose_name='Тип новина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създадена на')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'db_table': 'news',
            },
        ),
    ]
