# Generated by Django 6.0 on 2025-12-21 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Име на зона')),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='news.news', verbose_name='Новина')),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зони',
                'db_table': 'news_zones',
            },
        ),
        migrations.CreateModel(
            name='ZonePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Географска ширина')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Географска дължина')),
                ('point_order', models.PositiveIntegerField(verbose_name='Ред на точката')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='news.newszone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Точка на зона',
                'verbose_name_plural': 'Точки на зона',
                'db_table': 'zone_points',
                'ordering': ['point_order'],
            },
        ),
    ]
