# Generated by Django 6.0 on 2026-04-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newszone_zonepoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source_type',
            field=models.CharField(choices=[('EMERGENCY', 'Бедствие / Опасност'), ('WATER_URGENT', 'Авария - Водоснабдяване'), ('WATER_PLANNED', 'Планов ремонт - ВиК'), ('ELEC_URGENT', 'Авария - Електрозахранване'), ('ELEC_PLANNED', 'Планов ремонт - Електро'), ('ROAD_WORKS', 'Ремонт на пътната мрежа'), ('TRAFFIC', 'Промяна в движението'), ('MUNICIPAL', 'Общинско съобщение'), ('OTHER', 'Други')], max_length=20, verbose_name='Тип новина'),
        ),
    ]
