# Generated by Django 6.0 on 2025-12-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Име на зона')),
                ('coordinates', models.JSONField(verbose_name='Координати (polygon)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създадена на')),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зони',
                'db_table': 'zones',
            },
        ),
    ]
