# Generated by Django 6.0 on 2026-02-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.IntegerField(verbose_name='ID на новина')),
                ('operation_type', models.CharField(choices=[('CREATE', 'Създаване'), ('UPDATE', 'Промяна'), ('DELETE', 'Изтриване')], max_length=10, verbose_name='Тип операция')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='Стари данни')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='Нови данни')),
                ('created_at', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Лог на новина',
                'verbose_name_plural': 'Логове на новини',
                'db_table': 'news_audit',
            },
        ),
        migrations.CreateModel(
            name='SignalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_id', models.IntegerField(verbose_name='ID на сигнал')),
                ('operation_type', models.CharField(choices=[('CREATE', 'Създаване'), ('UPDATE', 'Промяна'), ('DELETE', 'Изтриване')], max_length=10, verbose_name='Тип операция')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='Стари данни')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='Нови данни')),
                ('created_at', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Лог на сигнал',
                'verbose_name_plural': 'Логове на сигнали',
                'db_table': 'signals_audit',
            },
        ),
    ]
