# Generated by Django 6.0 on 2025-12-21 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заглавие')),
                ('description', models.TextField(verbose_name='Описание')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Географска ширина')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Географска дължина')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('OPEN', 'Отворен'), ('IN_PROGRESS', 'В процес'), ('RESOLVED', 'Решен'), ('REJECTED', 'Отхвърлен')], default='OPEN', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създаден на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последна промяна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='signals.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to=settings.AUTH_USER_MODEL, verbose_name='Подаден от')),
            ],
            options={
                'verbose_name': 'Сигнал',
                'verbose_name_plural': 'Сигнали',
                'db_table': 'signals',
            },
        ),
    ]
