# Generated by Django 6.0 on 2025-12-21 16:35

import apps.signals.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_alter_category_options_signal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.signals.models.signal_image_upload_path, verbose_name='Снимка')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Качена на')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='signals.signal', verbose_name='Сигнал')),
            ],
            options={
                'verbose_name': 'Снимка към сигнал',
                'verbose_name_plural': 'Снимки към сигнали',
                'db_table': 'signal_images',
            },
        ),
    ]
