# Generated by Django 6.0 on 2026-02-25 08:45

import apps.signals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalimage',
            name='image',
            field=models.ImageField(upload_to=apps.signals.models.signal_image_upload_path, validators=[apps.signals.models.validate_image_size], verbose_name='Снимка'),
        ),
    ]
